# Generated by Django 3.1.4 on 2020-12-19 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('del_person', 'Apagar User'),)},
        ),
    ]
