# Generated by Django 3.1.4 on 2021-03-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20201219_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'telefone')},
        ),
    ]
