# Generated by Django 3.1.3 on 2020-12-01 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20180210_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor',
        ),
    ]
