# Generated by Django 3.1.4 on 2020-12-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_valor_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'User set NF-e'),)},
        ),
    ]
