# Generated by Django 3.1.3 on 2020-12-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_venda_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='impostos',
            field=models.FloatField(),
        ),
    ]
