# Generated by Django 3.1.4 on 2020-12-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20201219_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'User set NF-e'), ('ver_dashboard', 'Pode ver o DASHBOARD'))},
        ),
    ]
