# Generated by Django 3.1.4 on 2021-02-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20201219_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
