# Generated by Django 3.1.4 on 2021-02-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20210225_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='impostos',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='status',
        ),
    ]
