# Generated by Django 3.1.4 on 2021-03-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0008_venda_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itendopedido',
            options={'verbose_name': 'Item do pedido', 'verbose_name_plural': 'Itens do pedido'},
        ),
    ]
