# Generated by Django 3.1.4 on 2021-03-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0012_remove_itendopedido_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itendopedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
